//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkChronicle.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkChronicle.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the App.
        /// </summary>
        public static string AboutTheApp {
            get {
                return ResourceManager.GetString("AboutTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while calculating the shifts. Try again!.
        /// </summary>
        public static string AnErrorOccurredWhileCalculatingTheShifts {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileCalculatingTheShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A schedule for the month {0} already exists. Do you want to overwrite it?.
        /// </summary>
        public static string AScheduleForTheMonthAlreadyExistsToOverwrite {
            get {
                return ResourceManager.GetString("AScheduleForTheMonthAlreadyExistsToOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At this moment work hours are available up to year 2025 (included)..
        /// </summary>
        public static string AtThisMomentWorkHoursAvailableTo2025 {
            get {
                return ResourceManager.GetString("AtThisMomentWorkHoursAvailableTo2025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Schedule for {0} {1}.
        /// </summary>
        public static string CalendarWorkScheduleFor {
            get {
                return ResourceManager.GetString("CalendarWorkScheduleFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensate &amp; Edit Schedule.
        /// </summary>
        public static string CompensateEditSchedule {
            get {
                return ResourceManager.GetString("CompensateEditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensate Selected Shift.
        /// </summary>
        public static string CompensateSelectedShift {
            get {
                return ResourceManager.GetString("CompensateSelectedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new schedule.
        /// </summary>
        public static string CreateANewSchedule {
            get {
                return ResourceManager.GetString("CreateANewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day shift.
        /// </summary>
        public static string DayShift {
            get {
                return ResourceManager.GetString("DayShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected schedule.
        /// </summary>
        public static string DeleteSelectedSchedule {
            get {
                return ResourceManager.GetString("DeleteSelectedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit and Save Schedule.
        /// </summary>
        public static string EditAndSaveSchedule {
            get {
                return ResourceManager.GetString("EditAndSaveSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Selected Shift.
        /// </summary>
        public static string EditSelectedShift {
            get {
                return ResourceManager.GetString("EditSelectedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first shift:.
        /// </summary>
        public static string EnterFirstShift {
            get {
                return ResourceManager.GetString("EnterFirstShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter shift cycle pattern:.
        /// </summary>
        public static string EnterShiftCyclePattern {
            get {
                return ResourceManager.GetString("EnterShiftCyclePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Schedule.
        /// </summary>
        public static string GenerateSchedule {
            get {
                return ResourceManager.GetString("GenerateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back to Main.
        /// </summary>
        public static string GoBackToMain {
            get {
                return ResourceManager.GetString("GoBackToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} hours of overtime, you can choose which shift to compensate..
        /// </summary>
        public static string HourMessageYouHaveHoursOfOvertime {
            get {
                return ResourceManager.GetString("HourMessageYouHaveHoursOfOvertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} hours under the total hours for the month. .
        /// </summary>
        public static string HourMessageYouHaveUnderTheTotalHoursForTheMonth {
            get {
                return ResourceManager.GetString("HourMessageYouHaveUnderTheTotalHoursForTheMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a 24HourDay schedule, {0} can&apos;t be select as first shift, please select {1}..
        /// </summary>
        public static string InA24HourdDayScheduleCantBeSelectedAsFirstShift {
            get {
                return ResourceManager.GetString("InA24HourdDayScheduleCantBeSelectedAsFirstShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a Day-Day schedule, {0} can&apos;t be select as first shift, please select {1}..
        /// </summary>
        public static string InADayDayScheduleCantBeSelectFirstShift {
            get {
                return ResourceManager.GetString("InADayDayScheduleCantBeSelectFirstShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a saved schedule.
        /// </summary>
        public static string LoadaSavedSchedule {
            get {
                return ResourceManager.GetString("LoadaSavedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load selected schedule.
        /// </summary>
        public static string LoadSelectedSchedule {
            get {
                return ResourceManager.GetString("LoadSelectedSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night shift.
        /// </summary>
        public static string NightShift {
            get {
                return ResourceManager.GetString("NightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No save schedule found!.
        /// </summary>
        public static string NoSaveScheduleFound {
            get {
                return ResourceManager.GetString("NoSaveScheduleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a schedule..
        /// </summary>
        public static string PleaseSelectASchedule {
            get {
                return ResourceManager.GetString("PleaseSelectASchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a work schedule first!.
        /// </summary>
        public static string PleaseSelectAScheduleFirst {
            get {
                return ResourceManager.GetString("PleaseSelectAScheduleFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid work shift!.
        /// </summary>
        public static string PleaseSelectAValidWorkShift {
            get {
                return ResourceManager.GetString("PleaseSelectAValidWorkShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem.
        /// </summary>
        public static string ReportAProblem {
            get {
                return ResourceManager.GetString("ReportAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Schedule.
        /// </summary>
        public static string SaveSchedule {
            get {
                return ResourceManager.GetString("SaveSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule deleted successfully!.
        /// </summary>
        public static string ScheduleDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ScheduleDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Exists.
        /// </summary>
        public static string ScheduleExists {
            get {
                return ResourceManager.GetString("ScheduleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule not found, please try again!.
        /// </summary>
        public static string ScheduleNotFoundPleaseTryAgain {
            get {
                return ResourceManager.GetString("ScheduleNotFoundPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected shift is compensated..
        /// </summary>
        public static string SelectedShiftIsCompensated {
            get {
                return ResourceManager.GetString("SelectedShiftIsCompensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected shift is a working shift, again..
        /// </summary>
        public static string SelectedShiftIsUnCompensated {
            get {
                return ResourceManager.GetString("SelectedShiftIsUnCompensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select First Shift.
        /// </summary>
        public static string SelectFirstShift {
            get {
                return ResourceManager.GetString("SelectFirstShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Shift Pattern.
        /// </summary>
        public static string SelectShiftPattern {
            get {
                return ResourceManager.GetString("SelectShiftPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the starting day of your work cycle:.
        /// </summary>
        public static string SelectStartingDayWorkCycle {
            get {
                return ResourceManager.GetString("SelectStartingDayWorkCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the starting time for the Day Shift:.
        /// </summary>
        public static string SelectStartingTimeForDayShift {
            get {
                return ResourceManager.GetString("SelectStartingTimeForDayShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the starting time for the Night Shift:.
        /// </summary>
        public static string SelectStartingTimeForNigthShift {
            get {
                return ResourceManager.GetString("SelectStartingTimeForNigthShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Total Shift Hours:.
        /// </summary>
        public static string SelectTotalShiftHours {
            get {
                return ResourceManager.GetString("SelectTotalShiftHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, generate new schedule..
        /// </summary>
        public static string SomethingWentWrongGeneratedNewSchedule {
            get {
                return ResourceManager.GetString("SomethingWentWrongGeneratedNewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again!.
        /// </summary>
        public static string SomethingWentWrongPleaseTryAgain {
            get {
                return ResourceManager.GetString("SomethingWentWrongPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a calendar for the {0} {1}!.
        /// </summary>
        public static string TextMessageThisIsACalendar {
            get {
                return ResourceManager.GetString("TextMessageThisIsACalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your total hours for the month {0} are {1} hours , the working hours for that month are: {2} hours..
        /// </summary>
        public static string TextMessageTotalHoursAreForTheMonthAndWorkingHours {
            get {
                return ResourceManager.GetString("TextMessageTotalHoursAreForTheMonthAndWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app language has been changed to {0}..
        /// </summary>
        public static string TheAppLanguageHasBeenChanged {
            get {
                return ResourceManager.GetString("TheAppLanguageHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total shift hours must be a positive number!.
        /// </summary>
        public static string TheTotalShiftHoursMustBepositiveNumber {
            get {
                return ResourceManager.GetString("TheTotalShiftHoursMustBepositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Rest Day..
        /// </summary>
        public static string ThisIsARestDay {
            get {
                return ResourceManager.GetString("ThisIsARestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a rest day and it can&apos;t be compensated!.
        /// </summary>
        public static string ThisIsARestDayAndItCantBeCompensated {
            get {
                return ResourceManager.GetString("ThisIsARestDayAndItCantBeCompensated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shift is not in the current month..
        /// </summary>
        public static string ThisShiftIsNotInTheCurrentMonth {
            get {
                return ResourceManager.GetString("ThisShiftIsNotInTheCurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Chronicle.
        /// </summary>
        public static string WelcomeToTheWorkChronicle {
            get {
                return ResourceManager.GetString("WelcomeToTheWorkChronicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have loaded the {0} schedule for the {1}..
        /// </summary>
        public static string YouHaveLoadedTheScheduleForThe {
            get {
                return ResourceManager.GetString("YouHaveLoadedTheScheduleForThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no schedule for this month..
        /// </summary>
        public static string YouHaveNoScheduleForThisMonth {
            get {
                return ResourceManager.GetString("YouHaveNoScheduleForThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your schedule has been saved..
        /// </summary>
        public static string YourScheduleHasBeenSaved {
            get {
                return ResourceManager.GetString("YourScheduleHasBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shift has been edit..
        /// </summary>
        public static string YourShiftHasBeenEdit {
            get {
                return ResourceManager.GetString("YourShiftHasBeenEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shift has been edit. If you don&apos;t want to lose the schedule save it first!..
        /// </summary>
        public static string YourShiftHasBeenEditSaveItFirst {
            get {
                return ResourceManager.GetString("YourShiftHasBeenEditSaveItFirst", resourceCulture);
            }
        }
    }
}
